---
title: "Contributing Guidlines for `heritable`"
format: html
---

## Welcome!

We are so excited that you are interested in contributing to `heritable`. In these contributing guidelines you'll find infomation on: 

- Quickstart for contributors
- Types of contributions 
- Development workflow 
- Code style
- Documentation and tests
- Dependencies + compatibility
- Code of Conduct

### Quickstart for contributors

1. Fork the repository and clone it to your local machine.
2. Create a new branch for your feature or bug fix.
3. Make your changes, write tests for changes and commit them with clear messages.
4. Push your branch to your forked repository.
5. Open a pull request against the main repository's `main` branch.

### Types of contributions

Contributions can be in the form of:
- Bug fixes
- Addition or edits to documentation,
- Addition or refinement of tests, 
- Performance improvements

Take a look at the Github Issues for outstanding bugs and features. 

If you have a specific request, please open an issue. Provide a minimal, reproducible example to help us understand the problem.

If your idea is not fully formed, open a [discussion](https://github.com/anu-aagi/heritable/discussions). We can all help flesh it out before breaking it up into actionable issues.

### Development toolkit and workflow 

The main packages we use for development are `usethis`, `devtools`, `testthat`, `roxygen2`. We follow the best practices for R package development as outlined in [R Packages](https://r-pkgs.org/).

. We follow a feature branch workflow where each new feature or bug fix is developed in its own branch.

To learn more about branching and pull requests, check out the [GitHub Flow](https://guides.github.com/introduction/flow/) guide.

This allows us to keep the main branch stable and makes it easier to review and merge changes. Pull requests also allow for discussion and feedback on proposed changes before they are merged into the main codebase.

### Code style

Code style is important for readability and maintainability. We generally follow the tidyverse style guide as outlined in [styler](https://styler.r-lib.org/articles/styler.html).

We understand it may not always be possible to follow a particular style perfectly. To encourage contributions, we encourage you to try and  maintainers/reviewers can support the PR process. At times, we may use `styler` to automatically format code.

We like **modularity** and readability over long, complex functions. If you find yourself writing a function that is getting too long or doing too many things, consider breaking it up into smaller helper functions.

### Documentation and tests

Every function including internal helpers need docs using roxygen2. 

Consider test-driven development 

Fixtures of asreml model objects

### Dependencies 

asreml is properiarty

### Code of Conduct

We value open and respectful communication in successful collaborations. 

We are humans before we are statisticians, before we are programmers, so communicate with each other kindly.


